version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2024.01.1
    steps:
      - checkout
      - run:
          name: Instalar Ninja
          command: sudo apt-get install -y -qq ninja-build
      - run:
          name: Compilar APK
          command: |
            cd app
            gradle assembleDebug --no-daemon
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apk/

workflows:
  version: 2
  build:
    jobs:
      - build
